---

- name: "Check if swarm cluster exists"
  ansible.builtin.stat:
    path: /var/lib/docker/swarm/state.json
  register: swarm_state_file

- name: Setting up Swarm
  # Similar to a Try/Except
  # https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html#blocks-error-handling
  block:
    - name: Initiating the swarm with default parameters
      # https://docs.ansible.com/ansible/latest/modules/docker_swarm_module.html
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ swarm_ip_address }}"
      register: init_swarm

    - name: "set fact: join token worker"
      ansible.builtin.set_fact:
        join_token_worker: "{{ init_swarm.swarm_facts.JoinTokens.Worker }}"

    - name: "set fact: join token manager"
      ansible.builtin.set_fact:
        join_token_manager: "{{ init_swarm.swarm_facts.JoinTokens.Manager }}"
  rescue:
    - name: Initiating the swarm with default parameters
      # https://docs.ansible.com/ansible/latest/modules/command_module.html
      ansible.builtin.command: "docker swarm init --advertise-addr {{ swarm_ip_address }}"
      ignore_errors: yes

    - name: Getting join manager token from existing Swarm
      # https://docs.ansible.com/ansible/latest/modules/command_module.html
      ansible.builtin.command: docker swarm join-token manager -q
      register: join_token_manager_command

    - name: Getting join worker token from existing Swarm
      # https://docs.ansible.com/ansible/latest/modules/command_module.html
      ansible.builtin.command: docker swarm join-token worker -q
      register: join_token_worker_command

    - name: "set fact: join_token_manager"
      ansible.builtin.set_fact:
        join_token_manager: "{{ join_token_manager_command['stdout'] }}"

    - name: "set fact: join_token_worker"
      ansible.builtin.set_fact:
        join_token_worker: "{{ join_token_worker_command['stdout'] }}"
  when: not swarm_state_file.stat.exists

- name: Getting join tokens
  block:
    - name: Getting join manager token from existing Swarm
      # https://docs.ansible.com/ansible/latest/modules/command_module.html
      ansible.builtin.command: docker swarm join-token manager -q
      register: join_token_manager_command

    - name: Getting join worker token from existing Swarm
      # https://docs.ansible.com/ansible/latest/modules/command_module.html
      ansible.builtin.command: docker swarm join-token worker -q
      register: join_token_worker_command

    - name: "set fact: join_token_manager"
      ansible.builtin.set_fact:
        join_token_manager: "{{ join_token_manager_command['stdout'] }}"

    - name: "set fact: join_token_worker"
      ansible.builtin.set_fact:
        join_token_worker: "{{ join_token_worker_command['stdout'] }}"
  when: swarm_state_file.stat.exists